name: Build Android APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
      - name: Build APK
        run: |
          cd mobile
          flutter pub get
          flutter build apk --release
      - uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: mobile/build/app/outputs/flutter-apk/app-release.apk
